# Generated by cucumber-sinatra. (2013-12-11 09:59:12 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'wavesurfer.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Wavesurfer

class WavesurferWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  WavesurferWorld.new
end
